# Generated by Django 2.0.5 on 2021-08-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_insurance_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmerid', models.CharField(max_length=300)),
                ('farmername', models.CharField(max_length=300)),
                ('product_name', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('product_image', models.FileField(upload_to='')),
            ],
        ),
    ]
