# Generated by Django 2.0.5 on 2021-08-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_insurance_details_insurance_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance_details',
            old_name='seed_name',
            new_name='status',
        ),
    ]
