# Generated by Django 2.0.5 on 2021-08-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20210804_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_details',
            name='seed_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
