# Generated by Django 2.0.5 on 2023-05-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_insurance_details_seed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer_reg',
            name='gender',
        ),
    ]
