# Generated by Django 2.0.5 on 2021-07-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='insurance_company',
            new_name='insurance_company_details',
        ),
    ]
