# Generated by Django 2.0.5 on 2021-07-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company', '0002_auto_20210729_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='insurance_company_details',
            new_name='insurance_company_register',
        ),
    ]
