# Generated by Django 2.0.5 on 2021-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seed_upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seed_name', models.CharField(max_length=300)),
                ('number_pieces', models.CharField(max_length=300)),
                ('brand_name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('product_image', models.FileField(upload_to='')),
            ],
        ),
    ]
